### ISSUE TITLE
hsdp_notification_topics as a change for every plan

### ISSUE THREAD

**Issue by prince-melvin** [philips-software/terraform-provider-hsdp#165] opened 2022-02-01 11:46 UTC
The data source hsdp_notification_topics is considering as a change for every plan eventhough there is no change in the inputs

module.dicomstore_onboard[0].data.hsdp_notification_topics.notificationSeriesTopics["8a7b348e-57ec-4c62-8f21-7b6c3da1e808"] will be read during apply
   (config refers to values not yet known)
 <= data "hsdp_notification_topics" "notificationSeriesTopics"  {
      ~ id        = "notification_topics" -> (known after apply)
        name      = "dss-edisa-previewnew_8a7b348e-57ec-4c62-8f21-7b6c3da1e808_series"
      ~ topic_ids = [
          - "a89e15b4-a625-44f9-965d-a92f2797fd99",
        ] -> (known after apply)
    }

**Comment by loafoe** [comment] 2022-02-01 12:24
@prince-melvin are topics ID appearing and disappearing?

**Comment by prince-melvin** [comment] 2022-02-01 12:30
Not sure, the topic ids are remaining the same.
~ id = "notification_topics" -> (known after apply) not sure about this parameter.
Because we are giving only name as input,

data "hsdp_notification_topics" "notificationStudyTopics" {

  for_each = {
    for tenant in var.iam_tenant_orgs :
    tenant.id => tenant
  }
  
  name =  "dss-${local.dicomstoreInstance}_${each.key}_study"
  
  depends_on = [
    hsdp_iam_group.grp_notify_read,
    module.dicomstore_tenant_orgs_onboard
  ]

}

**Comment by prince-melvin** [comment] 2022-02-01 13:13
Already applied resources also are considering as a change in plan..due to some input change I guess.
 
https://github.com/philips-internal/edi-platform/runs/5008118726?check_suite_focus=true

**Comment by loafoe** [comment] 2022-02-01 15:16
> Plan: 84 to add, 108 to change, 0 to destroy.

😱 

Are the 108 changes due to the data sources returned different (ordered?) values?

**Comment by prince-melvin** [comment] 2022-02-02 05:16
yeah most of them :sweat:
Cacading changes because of change in data source

**Comment by loafoe** [comment] 2022-02-02 05:41
@prince-melvin I think I know what is wrong, it looks like the data source id is not unique. I'l try to reproduce and provide a fix later in the day

**Comment by loafoe** [comment] 2022-02-02 06:15
`0.29.8` contains a possible fix for this issue, if you can try it and report back. thx!

**Comment by prince-melvin** [comment] 2022-02-28 10:38
@loafoe Upgraded to the provider 0.29.8, still the same issue
https://github.com/philips-internal/edi-platform/actions/runs/1909702406

**Comment by loafoe** [comment] 2022-02-28 10:49
@prince-melvin Did you apply it at least once with `v0.29.8` ?

**Comment by prince-melvin** [comment] 2022-02-28 10:56
yeah applied it already

**Comment by yasar-m** [comment] 2022-03-01 02:41
@loafoe  sample plan after v0.29.8
  
  # module.dicomstore_onboard[0].data.hsdp_notification_topics.notificationSeriesTopics["0c9c952a-223d-4e94-a8d3-fba811a42bd3"] will be read during apply
  # (config refers to values not yet known)
 <= data "hsdp_notification_topics" "notificationSeriesTopics"  {
      ~ id        = "notification-topics-c820e225-3109-4d6b-bec5-e09af5d2e213" -> (known after apply)
        name      = "dss-edisa-previewnew_0c9c952a-223d-4e94-a8d3-fba811a42bd3_series"
      ~ topic_ids = [
          - "c820e225-3109-4d6b-bec5-e09af5d2e213",
        ] -> (known after apply)
    }

**Comment by loafoe** [comment] 2022-03-01 06:11
@yasar-m can you share the module definition itself?

**Comment by prince-melvin** [comment] 2022-03-01 06:38
https://github.com/philips-internal/edi-platform-modules/blob/main/modules/core/modules/dicomstore/dicom_notification_topics.tf

**Comment by loafoe** [comment] 2022-03-02 12:35
@prince-melvin @yasar-m after looking at your module I think I understand where the mismatch is happening. Essentially, you are using the `hsdp_notification_topics` (plural!) resource to look up a very specific topic based the unique name itself. 

The proper resource to use would actually be `hsdp_notification_topic` which ensures you get exactly one topic. 
Currently this resource only supports queries based on `topic_id` itself but I think this can be changed to also support a query by `name`. I will try implementing this shortly

**Comment by loafoe** [comment] 2022-03-02 20:17
@prince-melvin @yasar-m `v0.30.2` contains modifications as described in my earlier comment. If you can refactor your module to use the singular `hsdp_notification_topic` topic with the name as input you should get stable data sources:

```hcl
data "hsdp_notification_topic" "notificationSeriesTopics" {

  for_each = {
    for tenant in var.iam_tenant_orgs :
    tenant.id => tenant
  }

  name = "dss-${local.dicomstoreInstance}_${each.key}_series"

  depends_on = [
    hsdp_iam_group.grp_notify_read,
    module.dicomstore_tenant_orgs_onboard
  ]

}
```

**Comment by prince-melvin** [comment] 2022-03-03 05:32
> @prince-melvin @yasar-m `v0.30.2` contains modifications as described in my earlier comment. If you can refactor your module to use the singular `hsdp_notification_topic` topic with the name as input you should get stable data sources:
> 
> ```terraform
> data "hsdp_notification_topic" "notificationSeriesTopics" {
> 
>   for_each = {
>     for tenant in var.iam_tenant_orgs :
>     tenant.id => tenant
>   }
> 
>   name = "dss-${local.dicomstoreInstance}_${each.key}_series"
> 
>   depends_on = [
>     hsdp_iam_group.grp_notify_read,
>     module.dicomstore_tenant_orgs_onboard
>   ]
> 
> }
> ```

Great! Will update and let you know.Thanks

**Comment by prince-melvin** [comment] 2022-03-03 09:06
@loafoe still the same issue it seems

```
  # module.dicomstore_onboard[0].data.hsdp_notification_topic.notificationStudyTopics["780b5f5a-4b81-473a-be3a-ad0a136691ae"] will be read during apply
  # (config refers to values not yet known)
 <= data "hsdp_notification_topic" "notificationStudyTopics"  {
      ~ allowed_scopes = [] -> (known after apply)
      ~ description    = "dss-edisa-previewnew study notification" -> (known after apply)
      ~ id             = "910916e3-1429-4c65-8f79-3f5ac2c0b330" -> (known after apply)
      ~ is_auditable   = false -> (known after apply)
        name           = "dss-edisa-previewnew_780b5f5a-4b81-473a-be3a-ad0a136691ae_study"
      ~ producer_id    = "7a6447f7-d6c9-4eb5-b933-d0193dbefbe3" -> (known after apply)
      ~ scope          = "private" -> (known after apply)
    }
```

**Comment by loafoe** [comment] 2022-03-03 10:58
Hm, so this might be because you are using a `local` variable in the name. Can you factor this out?

I have tested all changes and I'm not seeing the behaviour you describe in any of my scripts.

**Comment by loafoe** [comment] 2022-03-25 08:08
@prince-melvin any update on the refactoring?

**Comment by prince-melvin** [comment] 2022-03-28 05:41
@loafoe we can close this issue as it is not a bug in this data source.
It is an issue if we use data source along with depends_on which makes it re-read all of it again which results in cascading changes(in plan phase only).
https://github.com/hashicorp/terraform/issues/17034
https://github.com/hashicorp/terraform/issues/11806

The notification-topic data source is working as expected.

**Closed** 2022-03-28 11:30 UTC
